- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 16
  ori_difficulties:
    ? !!python/tuple [-60, medium]
    : 30
    ? !!python/tuple [30, medium]
    : 30
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      EH43LAnOcD8=
    ? !!python/tuple [out, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      EH43LAnOcD8=
  stim_ids:
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE
  taskname: adaptive_orientation
  trigger_key: '5'
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6024157070147655
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.04909681778738029
  stimulusDuration: 1.5
  trial_count: 1
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.0850683932039118
  displayFB: true
  onset: 6.151512524802146
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.4543154487064093
  stimulusDuration: 1.5
  trial_count: 2
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6751640632239797
  displayFB: true
  onset: 10.190896366712467
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.05243094258434411
  stimulusDuration: 1.5
  trial_count: 3
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8637778968448995
  displayFB: true
  onset: 14.41849137252079
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.3571490016153992
  stimulusDuration: 1.5
  trial_count: 4
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.2287864305606393
  displayFB: true
  onset: 19.13941827098109
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  stimResponseInterval: 0.42893368376959384
  stimulusDuration: 1.5
  trial_count: 5
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.023293175955317436
  displayFB: true
  onset: 23.29713838531132
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.5018683253943204
  stimulusDuration: 1.5
  trial_count: 6
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7687060447100209
  displayFB: true
  onset: 27.322299886660957
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.5327733250694306
  stimulusDuration: 1.5
  trial_count: 7
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.21509278417613098
  displayFB: true
  onset: 32.12377925644041
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.5680593173153157
  stimulusDuration: 1.5
  trial_count: 8
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5217990712827176
  displayFB: true
  onset: 36.40693135793185
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stimResponseInterval: 0.26476962539653226
  stimulusDuration: 1.5
  trial_count: 9
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6652164755073859
  displayFB: true
  onset: 40.69350005461111
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.4772389130253488
  stimulusDuration: 1.5
  trial_count: 10
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.3611953316738705
  displayFB: true
  onset: 45.335955443143845
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.8487682531445413
  stimulusDuration: 1.5
  trial_count: 11
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.513604188204007
  displayFB: true
  onset: 50.045919027962256
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.3617843339587262
  stimulusDuration: 1.5
  trial_count: 12
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.3652126136371652
  displayFB: true
  onset: 54.42130755012499
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.8500062939183577
  stimulusDuration: 1.5
  trial_count: 13
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.30514128166055243
  displayFB: true
  onset: 59.13652645768052
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.26402348391906827
  stimulusDuration: 1.5
  trial_count: 14
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7215969098979786
  displayFB: true
  onset: 63.20569122326014
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.4083345324818328
  stimulusDuration: 1.5
  trial_count: 15
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5224623444229752
  displayFB: true
  onset: 67.83562266563995
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.3988083278373279
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
