- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 16
  ori_difficulties:
    ? !!python/tuple [-60, medium]
    : 30
    ? !!python/tuple [30, medium]
    : 30
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      EH43LAnOcD8=
    ? !!python/tuple [out, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      EH43LAnOcD8=
  stim_ids:
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE
  taskname: adaptive_orientation
  trigger_key: '5'
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.10611852136748268
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.7541648506270044
  stimulusDuration: 1.5
  trial_count: 1
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.30108274740016994
  displayFB: true
  onset: 6.360283371994488
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.7443493939614885
  stimulusDuration: 1.5
  trial_count: 2
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5479401339902386
  displayFB: true
  onset: 10.905715513356146
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.18678924516903084
  stimulusDuration: 1.5
  trial_count: 3
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8389777690647486
  displayFB: true
  onset: 15.140444892515415
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.017793116263850495
  stimulusDuration: 1.5
  trial_count: 4
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8350746983795028
  displayFB: true
  onset: 19.497215777844012
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.7431031183401013
  stimulusDuration: 1.5
  trial_count: 5
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6979909214159425
  displayFB: true
  onset: 24.575393594563614
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.6262012037542872
  stimulusDuration: 1.5
  trial_count: 6
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8231761321026672
  displayFB: true
  onset: 29.399585719733842
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.9622023020679595
  stimulusDuration: 1.5
  trial_count: 7
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7476110527650874
  displayFB: true
  onset: 34.68496415390447
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.8209775409267139
  stimulusDuration: 1.5
  trial_count: 8
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.2880352534530084
  displayFB: true
  onset: 39.75355274759627
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.3811134682104388
  stimulusDuration: 1.5
  trial_count: 9
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.08228575103593505
  displayFB: true
  onset: 43.922701469259714
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.9654830640366197
  stimulusDuration: 1.5
  trial_count: 10
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8518891795836483
  displayFB: true
  onset: 48.470470284332265
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.48406553130950036
  stimulusDuration: 1.5
  trial_count: 11
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5358230634249654
  displayFB: true
  onset: 53.30642499522541
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  stimResponseInterval: 0.797385664400454
  stimulusDuration: 1.5
  trial_count: 12
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9664274059091491
  displayFB: true
  onset: 58.139633723050835
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.9091788775537399
  stimulusDuration: 1.5
  trial_count: 13
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.770414821184854
  displayFB: true
  onset: 63.51524000651372
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.1279701599275629
  stimulusDuration: 1.5
  trial_count: 14
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.3220288577596915
  displayFB: true
  onset: 67.91362498762614
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.8295422071475707
  stimulusDuration: 1.5
  trial_count: 15
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5086409728153432
  displayFB: true
  onset: 72.5651960525334
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stimResponseInterval: 0.2996944552475098
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
