- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 16
  ori_difficulties:
    ? !!python/tuple [-60, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      yLhlWdxHJkA=
    ? !!python/tuple [30, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      yLhlWdxHJkA=
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, medium]
    : 0.06
    ? !!python/tuple [out, medium]
    : 0.06
  stim_ids:
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE
  taskname: adaptive_motion
  trigger_key: '5'
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7558051502231531
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stimResponseInterval: 0.5705043526478297
  stimulusDuration: 1.5
  trial_count: 1
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8206033291809074
  displayFB: true
  onset: 6.826309502870982
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.20631701310785033
  stimulusDuration: 1.5
  trial_count: 2
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.4750183216506674
  displayFB: true
  onset: 11.35322984515974
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.10854139571894883
  stimulusDuration: 1.5
  trial_count: 3
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9395298155808063
  displayFB: true
  onset: 15.436789562529356
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.299322429358753
  stimulusDuration: 1.5
  trial_count: 4
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.47118579770856084
  displayFB: true
  onset: 20.175641807468914
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.2092936002021022
  stimulusDuration: 1.5
  trial_count: 5
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.006128072712181631
  displayFB: true
  onset: 24.356121205379576
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.15479086284940546
  stimulusDuration: 1.5
  trial_count: 6
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9960989561132216
  displayFB: true
  onset: 28.017040140941162
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.8073106770963945
  stimulusDuration: 1.5
  trial_count: 7
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.3941105648280169
  displayFB: true
  onset: 33.32044977415078
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.4896907903664742
  stimulusDuration: 1.5
  trial_count: 8
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.470262301532165
  displayFB: true
  onset: 37.70425112934527
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.7699959248185362
  stimulusDuration: 1.5
  trial_count: 9
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6489612697575882
  displayFB: true
  onset: 42.44450935569597
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  stimResponseInterval: 0.5335033213445124
  stimulusDuration: 1.5
  trial_count: 10
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5590470916393815
  displayFB: true
  onset: 47.126973946798074
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.5503154507667967
  stimulusDuration: 1.5
  trial_count: 11
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7309191647639874
  displayFB: true
  onset: 51.73633648920425
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.2254821777175896
  stimulusDuration: 1.5
  trial_count: 12
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5141238665776231
  displayFB: true
  onset: 56.192737831685825
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.39595870342759176
  stimulusDuration: 1.5
  trial_count: 13
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9652398695305231
  displayFB: true
  onset: 60.60282040169104
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.6550717389348164
  stimulusDuration: 1.5
  trial_count: 14
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.23404834204177483
  displayFB: true
  onset: 65.72313201015638
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.285263125840136
  stimulusDuration: 1.5
  trial_count: 15
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.2103289874469807
  displayFB: true
  onset: 69.74244347803828
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.529458226777209
  stimulusDuration: 1.5
  trial_count: 16
  ts: motion
