- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 16
  ori_difficulties:
    ? !!python/tuple [-60, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      IlqQlErzKEA=
    ? !!python/tuple [30, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      IlqQlErzKEA=
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, medium]
    : 0.06
    ? !!python/tuple [out, medium]
    : 0.06
  stim_ids:
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE
  taskname: adaptive_motion
  trigger_key: '5'
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.42484184556938953
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.4431947267611094
  stimulusDuration: 1.5
  trial_count: 1
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.43178209620881147
  displayFB: true
  onset: 6.368036572330499
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.29871932273183344
  stimulusDuration: 1.5
  trial_count: 2
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6861182116641147
  displayFB: true
  onset: 10.598537991271144
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.3906385928514703
  stimulusDuration: 1.5
  trial_count: 3
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.2237964076159501
  displayFB: true
  onset: 15.175294795786728
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.7757533526954259
  stimulusDuration: 1.5
  trial_count: 4
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5644401863722532
  displayFB: true
  onset: 19.674844556098105
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.155979847045133
  stimulusDuration: 1.5
  trial_count: 5
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.34918805940065123
  displayFB: true
  onset: 23.89526458951549
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.23485560304868947
  stimulusDuration: 1.5
  trial_count: 6
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.21790791854922287
  displayFB: true
  onset: 27.97930825196483
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.09741051485382801
  stimulusDuration: 1.5
  trial_count: 7
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5662476421116507
  displayFB: true
  onset: 31.79462668536788
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.24838333313049066
  stimulusDuration: 1.5
  trial_count: 8
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.13484735610192033
  displayFB: true
  onset: 36.10925766061002
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.1132083738285008
  stimulusDuration: 1.5
  trial_count: 9
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.45199415276563903
  displayFB: true
  onset: 39.85731339054044
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.583379059389431
  stimulusDuration: 1.5
  trial_count: 10
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7548243928140539
  displayFB: true
  onset: 44.39268660269551
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.011787933734924039
  stimulusDuration: 1.5
  trial_count: 11
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.3757703643430592
  displayFB: true
  onset: 48.65929892924449
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.7688326370347998
  stimulusDuration: 1.5
  trial_count: 12
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.06920551131730213
  displayFB: true
  onset: 53.30390193062235
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stimResponseInterval: 0.6828594432745647
  stimulusDuration: 1.5
  trial_count: 13
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7518057484665599
  displayFB: true
  onset: 57.55596688521422
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.15755826417984753
  stimulusDuration: 1.5
  trial_count: 14
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.3532873041449326
  displayFB: true
  onset: 61.965330897860625
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.9366156540047583
  stimulusDuration: 1.5
  trial_count: 15
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.425451230596151
  displayFB: true
  onset: 66.75523385601032
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  stimResponseInterval: 0.03939202924654539
  stimulusDuration: 1.5
  trial_count: 16
  ts: motion
