- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 32
  ori_difficulties:
    ? !!python/tuple [-60, medium]
    : 30
    ? !!python/tuple [30, medium]
    : 30
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      YBybcOyycr8=
    ? !!python/tuple [out, medium]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      YBybcOyycr8=
  stim_ids:
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE
  taskname: adaptive_orientation
  trigger_key: '5'
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5024172251019947
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.8645457119454028
  stimulusDuration: 1.5
  trial_count: 1
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.12397164984536779
  displayFB: true
  onset: 6.866962937047397
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.23048769908980515
  stimulusDuration: 1.5
  trial_count: 2
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9107503931359706
  displayFB: true
  onset: 10.72142228598257
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.3317989258452342
  stimulusDuration: 1.5
  trial_count: 3
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5932544879563959
  displayFB: true
  onset: 15.463971604963774
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.642805786671286
  stimulusDuration: 1.5
  trial_count: 4
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.19589181803272782
  displayFB: true
  onset: 20.200031879591457
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.917067482793954
  stimulusDuration: 1.5
  trial_count: 5
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9514841333336561
  displayFB: true
  onset: 24.812991180418138
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stimResponseInterval: 0.8365276013667438
  stimulusDuration: 1.5
  trial_count: 6
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5332943165621686
  displayFB: true
  onset: 30.101002915118535
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.13023512655550373
  stimulusDuration: 1.5
  trial_count: 7
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5774087553939036
  displayFB: true
  onset: 34.26453235823621
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.06004668316238615
  stimulusDuration: 1.5
  trial_count: 8
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.1766375151720927
  displayFB: true
  onset: 38.4019877967925
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.4639283120935106
  stimulusDuration: 1.5
  trial_count: 9
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9651363638394561
  displayFB: true
  onset: 42.5425536240581
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.3202189734281997
  stimulusDuration: 1.5
  trial_count: 10
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.896633418132037
  displayFB: true
  onset: 47.32790896132576
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.6743327387147362
  stimulusDuration: 1.5
  trial_count: 11
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5499444179764876
  displayFB: true
  onset: 52.39887511817253
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.3261401692201743
  stimulusDuration: 1.5
  trial_count: 12
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6097298921525893
  displayFB: true
  onset: 56.7749597053692
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.6192407354060547
  stimulusDuration: 1.5
  trial_count: 13
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.05872569140655237
  displayFB: true
  onset: 61.503930332927844
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.42507517580669674
  stimulusDuration: 1.5
  trial_count: 14
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.3772389669180122
  displayFB: true
  onset: 65.4877312001411
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.8497129234757477
  stimulusDuration: 1.5
  trial_count: 15
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5116298018704204
  displayFB: true
  onset: 70.21468309053486
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: 1,
    speedStrength: medium}
  stimResponseInterval: 0.20578496871639662
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9868853723920905
  displayFB: true
  onset: 74.43209786112168
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.3118732343446795
  stimulusDuration: 1.5
  trial_count: 17
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8947717099590582
  displayFB: true
  onset: 79.23085646785844
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.8082648360866569
  stimulusDuration: 1.5
  trial_count: 18
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9485861398290103
  displayFB: true
  onset: 84.43389301390415
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.9206331614002659
  stimulusDuration: 1.5
  trial_count: 19
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.09257202788234797
  displayFB: true
  onset: 89.80311231513343
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  stimResponseInterval: 0.8785537770796901
  stimulusDuration: 1.5
  trial_count: 20
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.24920769659985398
  displayFB: true
  onset: 94.27423812009548
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.34076778594346746
  stimulusDuration: 1.5
  trial_count: 21
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7455929865625968
  displayFB: true
  onset: 98.3642136026388
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.5214384711541875
  stimulusDuration: 1.5
  trial_count: 22
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.3941500188159822
  displayFB: true
  onset: 103.13124506035558
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.21069200485353334
  stimulusDuration: 1.5
  trial_count: 23
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.4446174867522441
  displayFB: true
  onset: 107.2360870840251
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.63645741084813
  stimulusDuration: 1.5
  trial_count: 24
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6891946623585974
  displayFB: true
  onset: 111.81716198162547
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.2744994294343275
  stimulusDuration: 1.5
  trial_count: 25
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.25780314190713594
  displayFB: true
  onset: 116.2808560734184
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.49266887979765206
  stimulusDuration: 1.5
  trial_count: 26
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.16836450753565557
  displayFB: true
  onset: 120.5313280951232
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.5418204317920443
  stimulusDuration: 1.5
  trial_count: 27
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.13257954768208768
  displayFB: true
  onset: 124.7415130344509
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.6497657472410232
  stimulusDuration: 1.5
  trial_count: 28
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6936748550716698
  displayFB: true
  onset: 129.023858329374
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.8556411664202304
  stimulusDuration: 1.5
  trial_count: 29
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5681279220122044
  displayFB: true
  onset: 134.0731743508659
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium, speedDirection: -1,
    speedStrength: medium}
  stimResponseInterval: 0.9151020369704179
  stimulusDuration: 1.5
  trial_count: 30
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6490797245737232
  displayFB: true
  onset: 139.05640430984855
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stimResponseInterval: 0.41833564749032837
  stimulusDuration: 1.5
  trial_count: 31
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8703984046216706
  displayFB: true
  onset: 143.6238196819126
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  stimResponseInterval: 0.3015319545497259
  stimulusDuration: 1.5
  trial_count: 32
  ts: orientation
