- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 16
  ori_difficulties:
    ? !!python/tuple [-60, 0.775]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      dPMrMwlXIUA=
    ? !!python/tuple [30, 0.775]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      dPMrMwlXIUA=
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, 0.775]
    : 0.06
    ? !!python/tuple [out, 0.775]
    : 0.06
  stim_ids:
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE
  taskname: adaptive_motion
  trigger_key: '5'
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8915142643672636
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  stimResponseInterval: 0.00488772943892779
  stimulusDuration: 1.5
  trial_count: 1
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.5490781924811243
  displayFB: true
  onset: 6.396401993806192
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: 0.775,
    speedDirection: -1, speedStrength: 0.775}
  stimResponseInterval: 0.17159886621080422
  stimulusDuration: 1.5
  trial_count: 2
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.13067302466308428
  displayFB: true
  onset: 10.61707905249812
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stimResponseInterval: 0.2198546989122826
  stimulusDuration: 1.5
  trial_count: 3
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.2031837369838232
  displayFB: true
  onset: 14.467606776073486
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: 0.775,
    speedDirection: -1, speedStrength: 0.775}
  stimResponseInterval: 0.158689532737032
  stimulusDuration: 1.5
  trial_count: 4
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.19110583873597298
  displayFB: true
  onset: 18.32948004579434
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  stimResponseInterval: 0.7929711797903467
  stimulusDuration: 1.5
  trial_count: 5
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.1339601964805247
  displayFB: true
  onset: 22.813557064320662
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stimResponseInterval: 0.6723852225563518
  stimulusDuration: 1.5
  trial_count: 6
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8706856237527254
  displayFB: true
  onset: 27.11990248335754
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: 0.775,
    speedDirection: 1, speedStrength: 0.775}
  stimResponseInterval: 0.03047706233077574
  stimulusDuration: 1.5
  trial_count: 7
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8094774952550776
  displayFB: true
  onset: 31.521065169441037
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: 0.775,
    speedDirection: -1, speedStrength: 0.775}
  stimResponseInterval: 0.03651180251385511
  stimulusDuration: 1.5
  trial_count: 8
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.13282161940301074
  displayFB: true
  onset: 35.86705446720997
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stimResponseInterval: 0.15126571565618652
  stimulusDuration: 1.5
  trial_count: 9
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8666477761937625
  displayFB: true
  onset: 39.651141802269166
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: 0.775,
    speedDirection: 1, speedStrength: 0.775}
  stimResponseInterval: 0.6105767223369409
  stimulusDuration: 1.5
  trial_count: 10
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6037998935452422
  displayFB: true
  onset: 44.62836630079987
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: 0.775,
    speedDirection: 1, speedStrength: 0.775}
  stimResponseInterval: 0.7460482478395205
  stimulusDuration: 1.5
  trial_count: 11
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.6327766377100099
  displayFB: true
  onset: 49.47821444218463
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: 0.775,
    speedDirection: -1, speedStrength: 0.775}
  stimResponseInterval: 0.20022843318295314
  stimulusDuration: 1.5
  trial_count: 12
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7571700814101321
  displayFB: true
  onset: 53.81121951307759
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: 0.775,
    speedDirection: 1, speedStrength: 0.775}
  stimResponseInterval: 0.8401968811794016
  stimulusDuration: 1.5
  trial_count: 13
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.4921027934425828
  displayFB: true
  onset: 58.90858647566712
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  stimResponseInterval: 0.7378602035445794
  stimulusDuration: 1.5
  trial_count: 14
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7025529265548087
  displayFB: true
  onset: 63.63854947265428
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stimResponseInterval: 0.33504734719887896
  stimulusDuration: 1.5
  trial_count: 15
  ts: motion
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.40451426858171835
  displayFB: true
  onset: 68.17614974640797
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  stimResponseInterval: 0.48326389798354086
  stimulusDuration: 1.5
  trial_count: 16
  ts: motion
