- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 16
  ori_difficulties:
    ? !!python/tuple [-60, 0.775]
    : 30
    ? !!python/tuple [30, 0.775]
    : 30
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, 0.775]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      gLd3AsX0bj8=
    ? !!python/tuple [out, 0.775]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      gLd3AsX0bj8=
  stim_ids:
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  - {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE
  taskname: adaptive_orientation
  trigger_key: '5'
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.19798630964497566
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  stimResponseInterval: 0.48327434943642744
  stimulusDuration: 1.5
  trial_count: 1
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7299103255080466
  displayFB: true
  onset: 6.181260659081403
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: 0.775,
    speedDirection: 1, speedStrength: 0.775}
  stimResponseInterval: 0.3534889986986216
  stimulusDuration: 1.5
  trial_count: 2
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9791764388599775
  displayFB: true
  onset: 10.764659983288071
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: 0.775,
    speedDirection: 1, speedStrength: 0.775}
  stimResponseInterval: 0.9518170926818834
  stimulusDuration: 1.5
  trial_count: 3
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.883601833528443
  displayFB: true
  onset: 16.19565351482993
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  stimResponseInterval: 0.8348503285897677
  stimulusDuration: 1.5
  trial_count: 4
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.38723785635358055
  displayFB: true
  onset: 21.414105676948143
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: 0.775,
    speedDirection: 1, speedStrength: 0.775}
  stimResponseInterval: 0.23438786055104377
  stimulusDuration: 1.5
  trial_count: 5
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7909588627314992
  displayFB: true
  onset: 25.535731393852767
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: 0.775,
    speedDirection: -1, speedStrength: 0.775}
  stimResponseInterval: 0.9114917894620993
  stimulusDuration: 1.5
  trial_count: 6
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.931508027607471
  displayFB: true
  onset: 30.738182046046365
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: 0.775,
    speedDirection: -1, speedStrength: 0.775}
  stimResponseInterval: 0.4081414250509078
  stimulusDuration: 1.5
  trial_count: 7
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.7406692733481328
  displayFB: true
  onset: 35.57783149870475
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stimResponseInterval: 0.17952051848050565
  stimulusDuration: 1.5
  trial_count: 8
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9125694542867273
  displayFB: true
  onset: 39.99802129053339
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: 0.775,
    speedDirection: -1, speedStrength: 0.775}
  stimResponseInterval: 0.2191810418393696
  stimulusDuration: 1.5
  trial_count: 9
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.4143613216580613
  displayFB: true
  onset: 44.62977178665948
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stimResponseInterval: 0.5962722231151825
  stimulusDuration: 1.5
  trial_count: 10
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.006150293644004434
  displayFB: true
  onset: 49.140405331432724
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stimResponseInterval: 0.5509431033135483
  stimulusDuration: 1.5
  trial_count: 11
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.9010705309774951
  displayFB: true
  onset: 53.19749872839028
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  stimResponseInterval: 0.9075627290099706
  stimulusDuration: 1.5
  trial_count: 12
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.8641277591744418
  displayFB: true
  onset: 58.506131988377746
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: -1,
    speedStrength: 0.775}
  stimResponseInterval: 0.8613336423379807
  stimulusDuration: 1.5
  trial_count: 13
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.27554971722346655
  displayFB: true
  onset: 63.731593389890165
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: 0.775, speedDirection: 1,
    speedStrength: 0.775}
  stimResponseInterval: 0.8377677810509616
  stimulusDuration: 1.5
  trial_count: 14
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.4278051045695568
  displayFB: true
  onset: 68.34491088816459
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: 0.775,
    speedDirection: -1, speedStrength: 0.775}
  stimResponseInterval: 0.013866227683275056
  stimulusDuration: 1.5
  trial_count: 15
  ts: orientation
- FBDuration: 0.5
  FBonset: 0
  ITI: 0.985591828092055
  displayFB: true
  onset: 72.28658222041743
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: 0.775,
    speedDirection: 1, speedStrength: 0.775}
  stimResponseInterval: 0.5886095883901774
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
