- action_keys: [e, b, r, y]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 192
  ori_difficulties:
    ? !!python/tuple [-45, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      +f8QS+0rB0A=
    ? !!python/tuple [45, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      +f8QS+0rB0A=
  quit_key: q
  responseWindow: 1.0
  rp: 0.5
  speed_difficulties:
    ? !!python/tuple [in, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vr+4VssNfj8=
    ? !!python/tuple [out, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vr+4VssNfj8=
  states:
    0:
      dist_args: {loc: -0.3, scale: 0.37}
      ts: motion
    1:
      dist_args: {loc: 0.3, scale: 0.37}
      ts: orientation
  stim_ids:
  - {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stim_motions: [in, out]
  stim_oris: [-45, 45]
  subjid: IE
  taskname: cued_dot_task
  trigger_key: '5'
  ts_order: [motion, orientation]
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.4947266128758
  cueDuration: 0.75
  displayFB: false
  duration: 11.81550078419856
  onset: 2
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 3.8207741713227605
  stimulusDuration: 1.5
  trial_count: 1
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 7.420861270040492
  cueDuration: 0.75
  displayFB: false
  duration: 14.356792057553093
  onset: 13.81550078419856
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.435930787512601
  stimulusDuration: 1.5
  trial_count: 2
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.8912477852896439
  cueDuration: 0.75
  displayFB: false
  duration: 9.927833752123476
  onset: 28.172292841751656
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 3.536585966833832
  stimulusDuration: 1.5
  trial_count: 3
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.271973267747196
  cueDuration: 0.75
  displayFB: false
  duration: 10.226549628929803
  onset: 38.10012659387513
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 4.454576361182608
  stimulusDuration: 1.5
  trial_count: 4
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.962357777812899
  cueDuration: 0.75
  displayFB: false
  duration: 9.486286168565725
  onset: 48.326676222804934
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.023928390752825
  stimulusDuration: 1.5
  trial_count: 5
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.2777498546382056
  cueDuration: 0.75
  displayFB: false
  duration: 9.733309255646283
  onset: 57.81296239137066
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.9555594010080777
  stimulusDuration: 1.5
  trial_count: 6
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.8999403922744023
  cueDuration: 0.75
  displayFB: false
  duration: 7.231589843272843
  onset: 67.54627164701694
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.8316494509984411
  stimulusDuration: 1.5
  trial_count: 7
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.52667888580402
  cueDuration: 0.75
  displayFB: false
  duration: 8.690952505817094
  onset: 74.77786149028978
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: 1, speedStrength: 0.75}
  stimResponseInterval: 2.664273620013074
  stimulusDuration: 1.5
  trial_count: 8
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.77318778682753
  cueDuration: 0.75
  displayFB: false
  duration: 10.230815005451772
  onset: 83.46881399610687
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.9576272186242418
  stimulusDuration: 1.5
  trial_count: 9
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.025061629778685
  cueDuration: 0.75
  displayFB: false
  duration: 8.28014556057234
  onset: 93.69962900155865
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.7550839307936545
  stimulusDuration: 1.5
  trial_count: 10
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.0313845943090625
  cueDuration: 0.75
  displayFB: false
  duration: 13.904098857103957
  onset: 101.97977456213098
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 3.3727142627948936
  stimulusDuration: 1.5
  trial_count: 11
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.953803479055736
  cueDuration: 0.75
  displayFB: false
  duration: 12.93706767952996
  onset: 115.88387341923494
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.4832642004742242
  stimulusDuration: 1.5
  trial_count: 12
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.55494452859457
  cueDuration: 0.75
  displayFB: false
  duration: 10.057500135927146
  onset: 128.8209410987649
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.0025556073325754
  stimulusDuration: 1.5
  trial_count: 13
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.315148584209142
  cueDuration: 0.75
  displayFB: false
  duration: 10.201523894752295
  onset: 138.87844123469205
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.386375310543153
  stimulusDuration: 1.5
  trial_count: 14
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 9.737786867754114
  cueDuration: 0.75
  displayFB: false
  duration: 15.875722207010924
  onset: 149.07996512944433
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.637935339256809
  stimulusDuration: 1.5
  trial_count: 15
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.774528847438759
  cueDuration: 0.75
  displayFB: false
  duration: 7.361566652885902
  onset: 164.95568733645524
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.0870378054471426
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.756486234667097
  cueDuration: 0.75
  displayFB: false
  duration: 7.981633444805502
  onset: 172.31725398934114
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.7251472101384049
  stimulusDuration: 1.5
  trial_count: 17
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.3014531263286027
  cueDuration: 0.75
  displayFB: false
  duration: 12.115254663636264
  onset: 180.29888743414665
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 4.31380153730766
  stimulusDuration: 1.5
  trial_count: 18
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.473488010765055
  cueDuration: 0.75
  displayFB: false
  duration: 8.552406434986256
  onset: 192.41414209778293
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.578918424221201
  stimulusDuration: 1.5
  trial_count: 19
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.5506615924920601
  cueDuration: 0.75
  displayFB: false
  duration: 10.005403854731854
  onset: 200.9665485327692
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 3.954742262239794
  stimulusDuration: 1.5
  trial_count: 20
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.1510520499700188
  cueDuration: 0.75
  displayFB: false
  duration: 7.7232320663246075
  onset: 210.97195238750106
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.0721800163545883
  stimulusDuration: 1.5
  trial_count: 21
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.190740476490551
  cueDuration: 0.75
  displayFB: false
  duration: 8.114960929058334
  onset: 218.69518445382568
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.4242204525677824
  stimulusDuration: 1.5
  trial_count: 22
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.7008727839399373
  cueDuration: 0.75
  displayFB: false
  duration: 7.768320126207839
  onset: 226.810145382884
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.5674473422679017
  stimulusDuration: 1.5
  trial_count: 23
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 7.848997049103879
  cueDuration: 0.75
  displayFB: false
  duration: 13.04252009043347
  onset: 234.57846550909184
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.6935230413295908
  stimulusDuration: 1.5
  trial_count: 24
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.6489016461283312
  cueDuration: 0.75
  displayFB: false
  duration: 8.498105370046689
  onset: 247.6209855995253
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.349203723918357
  stimulusDuration: 1.5
  trial_count: 25
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 5.3044271635670395
  cueDuration: 0.75
  displayFB: false
  duration: 12.87243148015032
  onset: 256.119090969572
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 3.0680043165832807
  stimulusDuration: 1.5
  trial_count: 26
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 7.323215617021399
  cueDuration: 0.75
  displayFB: false
  duration: 14.137499956565684
  onset: 268.99152244972237
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.314284339544285
  stimulusDuration: 1.5
  trial_count: 27
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.640199263442441
  cueDuration: 0.75
  displayFB: false
  duration: 8.919443943864216
  onset: 283.1290224062881
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.7792446804217757
  stimulusDuration: 1.5
  trial_count: 28
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.8480555232639935
  cueDuration: 0.75
  displayFB: false
  duration: 8.085041500578559
  onset: 292.0484663501523
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.7369859773145647
  stimulusDuration: 1.5
  trial_count: 29
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.3752409569553328
  cueDuration: 0.75
  displayFB: false
  duration: 7.604744982327823
  onset: 300.13350785073084
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.7295040253724903
  stimulusDuration: 1.5
  trial_count: 30
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.279618401173291
  cueDuration: 0.75
  displayFB: false
  duration: 8.908925586426482
  onset: 307.73825283305865
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.1293071852531917
  stimulusDuration: 1.5
  trial_count: 31
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.317854909032462
  cueDuration: 0.75
  displayFB: false
  duration: 10.097884297220777
  onset: 316.64717841948516
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.280029388188314
  stimulusDuration: 1.5
  trial_count: 32
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 7.047657720531939
  cueDuration: 0.75
  displayFB: false
  duration: 12.244822106829305
  onset: 326.74506271670595
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.6971643862973662
  stimulusDuration: 1.5
  trial_count: 33
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.326344683367863
  cueDuration: 0.75
  displayFB: false
  duration: 9.62706102544527
  onset: 338.98988482353525
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 3.800716342077407
  stimulusDuration: 1.5
  trial_count: 34
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.9017291491425605
  cueDuration: 0.75
  displayFB: false
  duration: 7.611596330122449
  onset: 348.6169458489805
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.2098671809798875
  stimulusDuration: 1.5
  trial_count: 35
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.2235253944491005
  cueDuration: 0.75
  displayFB: false
  duration: 12.723525394449101
  onset: 356.22854217910293
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 6
  stimulusDuration: 1.5
  trial_count: 36
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.0225159094662675
  cueDuration: 0.75
  displayFB: false
  duration: 8.052142013833514
  onset: 368.95206757355203
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.5296261043672458
  stimulusDuration: 1.5
  trial_count: 37
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.0218628594666783
  cueDuration: 0.75
  displayFB: false
  duration: 7.1974845840248545
  onset: 377.00420958738556
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.6756217245581758
  stimulusDuration: 1.5
  trial_count: 38
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.8810945884720662
  cueDuration: 0.75
  displayFB: false
  duration: 7.176310793104397
  onset: 384.2016941714104
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.7952162046323302
  stimulusDuration: 1.5
  trial_count: 39
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.3172057289222927
  cueDuration: 0.75
  displayFB: false
  duration: 8.282301995722186
  onset: 391.3780049645148
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.4650962667998926
  stimulusDuration: 1.5
  trial_count: 40
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 12
  cueDuration: 0.75
  displayFB: false
  duration: 17.47806490427449
  onset: 399.660306960237
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.9780649042744888
  stimulusDuration: 1.5
  trial_count: 41
  ts: motion
