- action_keys: [e, b, r, y]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 192
  ori_difficulties:
    ? !!python/tuple [-45, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      +f8QS+0rB0A=
    ? !!python/tuple [45, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      +f8QS+0rB0A=
  quit_key: q
  responseWindow: 1.0
  rp: 0.5
  speed_difficulties:
    ? !!python/tuple [in, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vr+4VssNfj8=
    ? !!python/tuple [out, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vr+4VssNfj8=
  states:
    0:
      dist_args: {loc: -0.3, scale: 0.37}
      ts: orientation
    1:
      dist_args: {loc: 0.3, scale: 0.37}
      ts: motion
  stim_ids:
  - {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stim_motions: [in, out]
  stim_oris: [-45, 45]
  subjid: IE
  taskname: cued_dot_task
  trigger_key: '5'
  ts_order: [orientation, motion]
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.273357742813654
  cueDuration: 0.75
  displayFB: false
  duration: 10.176907295785124
  onset: 2
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 3.4035495529714708
  stimulusDuration: 1.5
  trial_count: 1
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 12
  cueDuration: 0.75
  displayFB: false
  duration: 17.85905357998759
  onset: 12.176907295785124
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.3590535799875922
  stimulusDuration: 1.5
  trial_count: 2
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 7.850741788984951
  cueDuration: 0.75
  displayFB: false
  duration: 13.905741869864094
  onset: 30.035960875772716
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.555000080879144
  stimulusDuration: 1.5
  trial_count: 3
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.5169897097913032
  cueDuration: 0.75
  displayFB: false
  duration: 7.892814496727668
  onset: 43.94170274563681
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.8758247869363653
  stimulusDuration: 1.5
  trial_count: 4
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.64988607643594
  cueDuration: 0.75
  displayFB: false
  duration: 14.377445284544168
  onset: 51.83451724236448
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.2275592081082265
  stimulusDuration: 1.5
  trial_count: 5
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 5.945283640079769
  cueDuration: 0.75
  displayFB: false
  duration: 12.16463774157144
  onset: 66.21196252690865
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.719354101491672
  stimulusDuration: 1.5
  trial_count: 6
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.418506809369577
  cueDuration: 0.75
  displayFB: false
  duration: 14.618375731298155
  onset: 78.37660026848009
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.6998689219285785
  stimulusDuration: 1.5
  trial_count: 7
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.763223926669665
  cueDuration: 0.75
  displayFB: false
  duration: 11.899591741719737
  onset: 92.99497599977825
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.6363678150500715
  stimulusDuration: 1.5
  trial_count: 8
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.491088504856278
  cueDuration: 0.75
  displayFB: false
  duration: 10.070320193344223
  onset: 104.89456774149798
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.0792316884879445
  stimulusDuration: 1.5
  trial_count: 9
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.0197768182084355
  cueDuration: 0.75
  displayFB: false
  duration: 8.047717843713944
  onset: 114.96488793484221
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 0.5279410255055086
  stimulusDuration: 1.5
  trial_count: 10
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 12
  cueDuration: 0.75
  displayFB: false
  duration: 17.998929389569177
  onset: 123.01260577855615
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.4989293895691778
  stimulusDuration: 1.5
  trial_count: 11
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.271060481467175
  cueDuration: 0.75
  displayFB: false
  duration: 10.039544206700398
  onset: 141.01153516812533
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.2684837252332248
  stimulusDuration: 1.5
  trial_count: 12
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.7276180761268485
  cueDuration: 0.75
  displayFB: false
  duration: 8.491477941182122
  onset: 151.05107937482575
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.263859865055273
  stimulusDuration: 1.5
  trial_count: 13
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.909271519730319
  cueDuration: 0.75
  displayFB: false
  duration: 8.200382981688563
  onset: 159.54255731600787
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.7911114619582427
  stimulusDuration: 1.5
  trial_count: 14
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.772454166578546
  cueDuration: 0.75
  displayFB: false
  duration: 13.934298465733537
  onset: 167.74294029769644
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.6618442991549918
  stimulusDuration: 1.5
  trial_count: 15
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 10.679759878567662
  cueDuration: 0.75
  displayFB: false
  duration: 17.050902779519255
  onset: 181.67723876342998
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.8711429009515939
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.588859426761893
  cueDuration: 0.75
  displayFB: false
  duration: 11.163860623395385
  onset: 198.72814154294923
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.075001196633492
  stimulusDuration: 1.5
  trial_count: 17
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.208481591027786
  cueDuration: 0.75
  displayFB: false
  duration: 9.071659098365728
  onset: 209.8920021663446
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.3631775073379415
  stimulusDuration: 1.5
  trial_count: 18
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.123771411186998
  cueDuration: 0.75
  displayFB: false
  duration: 8.17012809952914
  onset: 218.96366126471034
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.5463566883421422
  stimulusDuration: 1.5
  trial_count: 19
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.619429851441735
  cueDuration: 0.75
  displayFB: false
  duration: 9.039259652483123
  onset: 227.13378936423948
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.919829801041388
  stimulusDuration: 1.5
  trial_count: 20
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.936348397104
  cueDuration: 0.75
  displayFB: false
  duration: 15.392596045340879
  onset: 236.1730490167226
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.9562476482368785
  stimulusDuration: 1.5
  trial_count: 21
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.0906594765139073
  cueDuration: 0.75
  displayFB: false
  duration: 6.481012749491087
  onset: 251.56564506206345
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.8903532729771795
  stimulusDuration: 1.5
  trial_count: 22
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 5.87098366518382
  cueDuration: 0.75
  displayFB: false
  duration: 11.224870657066916
  onset: 258.04665781155455
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.8538869918830957
  stimulusDuration: 1.5
  trial_count: 23
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.0189597954645786
  cueDuration: 0.75
  displayFB: false
  duration: 7.018245973177727
  onset: 269.27152846862145
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.4992861777131485
  stimulusDuration: 1.5
  trial_count: 24
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.009994182011905
  cueDuration: 0.75
  displayFB: false
  duration: 8.412160939711924
  onset: 276.2897744417992
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.9021667577000194
  stimulusDuration: 1.5
  trial_count: 25
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.3533414781700883
  cueDuration: 0.75
  displayFB: false
  duration: 10.084590356116678
  onset: 284.70193538151113
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: 1, speedStrength: 0.75}
  stimResponseInterval: 3.2312488779465895
  stimulusDuration: 1.5
  trial_count: 26
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.5371348799513127
  cueDuration: 0.75
  displayFB: false
  duration: 9.696375579967018
  onset: 294.7865257376278
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.6592407000157063
  stimulusDuration: 1.5
  trial_count: 27
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.2294482666468327
  cueDuration: 0.75
  displayFB: false
  duration: 9.827053068233623
  onset: 304.48290131759484
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.0976048015867903
  stimulusDuration: 1.5
  trial_count: 28
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.270138633848613
  cueDuration: 0.75
  displayFB: false
  duration: 7.011788493815199
  onset: 314.30995438582846
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.2416498599665862
  stimulusDuration: 1.5
  trial_count: 29
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.2090097226025769
  cueDuration: 0.75
  displayFB: false
  duration: 8.910179177803197
  onset: 321.32174287964364
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 3.2011694552006213
  stimulusDuration: 1.5
  trial_count: 30
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.8235561940891847
  cueDuration: 0.75
  displayFB: false
  duration: 10.202282183952239
  onset: 330.2319220574468
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.878725989863053
  stimulusDuration: 1.5
  trial_count: 31
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.35032568394324
  cueDuration: 0.75
  displayFB: false
  duration: 7.63300939069698
  onset: 340.4342042413991
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.7826837067537393
  stimulusDuration: 1.5
  trial_count: 32
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.3344552201312188
  cueDuration: 0.75
  displayFB: false
  duration: 8.960950597130708
  onset: 348.06721363209607
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.1264953769994892
  stimulusDuration: 1.5
  trial_count: 33
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.3570558168508133
  cueDuration: 0.75
  displayFB: false
  duration: 6.66458778647079
  onset: 357.0281642292268
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.8075319696199768
  stimulusDuration: 1.5
  trial_count: 34
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.8777175579059475
  cueDuration: 0.75
  displayFB: false
  duration: 7.361258240047556
  onset: 363.6927520156976
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 0.983540682141609
  stimulusDuration: 1.5
  trial_count: 35
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.7680007616257516
  cueDuration: 0.75
  displayFB: false
  duration: 9.997392724896631
  onset: 371.05401025574514
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.7293919632708792
  stimulusDuration: 1.5
  trial_count: 36
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 5.624296370557785
  cueDuration: 0.75
  displayFB: false
  duration: 11.076567704014348
  onset: 381.0514029806418
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.9522713334565633
  stimulusDuration: 1.5
  trial_count: 37
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.953388735299978
  cueDuration: 0.75
  displayFB: false
  duration: 10.21585457903837
  onset: 392.12797068465613
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.7624658437383913
  stimulusDuration: 1.5
  trial_count: 38
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.567843231190982
  cueDuration: 0.75
  displayFB: false
  duration: 11.709552100747533
  onset: 402.3438252636945
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.641708869556552
  stimulusDuration: 1.5
  trial_count: 39
  ts: orientation
