- action_keys: [e, b, r, y]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 192
  ori_difficulties:
    ? !!python/tuple [-45, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      +f8QS+0rB0A=
    ? !!python/tuple [45, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      +f8QS+0rB0A=
  quit_key: q
  responseWindow: 1.0
  rp: 0.5
  speed_difficulties:
    ? !!python/tuple [in, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vr+4VssNfj8=
    ? !!python/tuple [out, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vr+4VssNfj8=
  states:
    0:
      dist_args: {loc: -0.3, scale: 0.37}
      ts: orientation
    1:
      dist_args: {loc: 0.3, scale: 0.37}
      ts: motion
  stim_ids:
  - {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stim_motions: [in, out]
  stim_oris: [-45, 45]
  subjid: IE
  taskname: cued_dot_task
  trigger_key: '5'
  ts_order: [orientation, motion]
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.5071454126030934
  cueDuration: 0.75
  displayFB: false
  duration: 9.504287837558724
  onset: 2
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.4971424249556313
  stimulusDuration: 1.5
  trial_count: 1
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.779771461304938
  cueDuration: 0.75
  displayFB: false
  duration: 15.29561633888689
  onset: 11.504287837558724
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 4.015844877581953
  stimulusDuration: 1.5
  trial_count: 2
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.2972210143834664
  cueDuration: 0.75
  displayFB: false
  duration: 9.072190489306703
  onset: 26.799904176445615
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.2749694749232352
  stimulusDuration: 1.5
  trial_count: 3
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.5560994341392034
  cueDuration: 0.75
  displayFB: false
  duration: 8.840163678142954
  onset: 35.872094665752314
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.78406424400375
  stimulusDuration: 1.5
  trial_count: 4
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.951161972491262
  cueDuration: 0.75
  displayFB: false
  duration: 9.926155897757631
  onset: 44.71225834389527
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: 1, speedStrength: 0.75}
  stimResponseInterval: 1.4749939252663702
  stimulusDuration: 1.5
  trial_count: 5
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 7.2857823436277265
  cueDuration: 0.75
  displayFB: false
  duration: 13.709053713171931
  onset: 54.6384142416529
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.9232713695442047
  stimulusDuration: 1.5
  trial_count: 6
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 12
  cueDuration: 0.75
  displayFB: false
  duration: 19.094054636297493
  onset: 68.34746795482484
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.5940546362974923
  stimulusDuration: 1.5
  trial_count: 7
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.066514142893947
  cueDuration: 0.75
  displayFB: false
  duration: 11.343401317098976
  onset: 87.44152259112232
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.7768871742050288
  stimulusDuration: 1.5
  trial_count: 8
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 7.584347270872194
  cueDuration: 0.75
  displayFB: false
  duration: 13.749824091796366
  onset: 98.7849239082213
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.6654768209241717
  stimulusDuration: 1.5
  trial_count: 9
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.4918348848704661
  cueDuration: 0.75
  displayFB: false
  duration: 7.349809116172011
  onset: 112.53474800001767
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.3579742313015444
  stimulusDuration: 1.5
  trial_count: 10
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.380297708440042
  cueDuration: 0.75
  displayFB: false
  duration: 8.67496213788325
  onset: 119.88455711618968
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.794664429443209
  stimulusDuration: 1.5
  trial_count: 11
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.129976153309431
  cueDuration: 0.75
  displayFB: false
  duration: 8.150023109783502
  onset: 128.55951925407294
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.520046956474071
  stimulusDuration: 1.5
  trial_count: 12
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 12
  cueDuration: 0.75
  displayFB: false
  duration: 21.07288113161175
  onset: 136.70954236385643
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 4.57288113161175
  stimulusDuration: 1.5
  trial_count: 13
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.271916258132722
  cueDuration: 0.75
  displayFB: false
  duration: 9.727230828994205
  onset: 157.78242349546818
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.955314570861482
  stimulusDuration: 1.5
  trial_count: 14
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 10.219247657465015
  cueDuration: 0.75
  displayFB: false
  duration: 18.835349917107617
  onset: 167.5096543244624
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 4.116102259642601
  stimulusDuration: 1.5
  trial_count: 15
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.5024863780983628
  cueDuration: 0.75
  displayFB: false
  duration: 11.449757585207331
  onset: 186.34500424157
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 5.44727120710897
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.3859894570946016
  cueDuration: 0.75
  displayFB: false
  duration: 6.808137930253204
  onset: 197.79476182677732
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.9221484731586017
  stimulusDuration: 1.5
  trial_count: 17
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.29755224781051
  cueDuration: 0.75
  displayFB: false
  duration: 13.830136256112691
  onset: 204.6028997570305
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.0325840083021818
  stimulusDuration: 1.5
  trial_count: 18
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.2201955841598338
  cueDuration: 0.75
  displayFB: false
  duration: 11.518607409682113
  onset: 218.4330360131432
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 4.7984118255222805
  stimulusDuration: 1.5
  trial_count: 19
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.3545745354908096
  cueDuration: 0.75
  displayFB: false
  duration: 6.476172147174256
  onset: 229.95164342282533
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.6215976116834461
  stimulusDuration: 1.5
  trial_count: 20
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.952950411840174
  cueDuration: 0.75
  displayFB: false
  duration: 8.191936907344614
  onset: 236.42781556999958
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.7389864955044401
  stimulusDuration: 1.5
  trial_count: 21
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.452171831414319
  cueDuration: 0.75
  displayFB: false
  duration: 15.779945693727468
  onset: 244.6197524773442
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.827773862313149
  stimulusDuration: 1.5
  trial_count: 22
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.452413152719867
  cueDuration: 0.75
  displayFB: false
  duration: 8.49608033724465
  onset: 260.3996981710717
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.5436671845247827
  stimulusDuration: 1.5
  trial_count: 23
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.6359476071769135
  cueDuration: 0.75
  displayFB: false
  duration: 7.641482115030422
  onset: 268.8957785083163
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.5055345078535085
  stimulusDuration: 1.5
  trial_count: 24
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.1461991232926874
  cueDuration: 0.75
  displayFB: false
  duration: 7.531057440331943
  onset: 276.53726062334675
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.8848583170392557
  stimulusDuration: 1.5
  trial_count: 25
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.365700182414322
  cueDuration: 0.75
  displayFB: false
  duration: 10.071272766381478
  onset: 284.0683180636787
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.2055725839671554
  stimulusDuration: 1.5
  trial_count: 26
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.675623393753359
  cueDuration: 0.75
  displayFB: false
  duration: 7.228638389319644
  onset: 294.1395908300602
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.0530149955662855
  stimulusDuration: 1.5
  trial_count: 27
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.270063649981774
  cueDuration: 0.75
  displayFB: false
  duration: 7.28865073327316
  onset: 301.3682292193798
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.5185870832913855
  stimulusDuration: 1.5
  trial_count: 28
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 12
  cueDuration: 0.75
  displayFB: false
  duration: 21.144334067406497
  onset: 308.656879952653
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 4.644334067406499
  stimulusDuration: 1.5
  trial_count: 29
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.6893548360497557
  cueDuration: 0.75
  displayFB: false
  duration: 8.807644504847714
  onset: 329.8012140200595
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.6182896687979587
  stimulusDuration: 1.5
  trial_count: 30
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.8434974118683318
  cueDuration: 0.75
  displayFB: false
  duration: 9.49664701305729
  onset: 338.6088585249072
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 3.153149601188958
  stimulusDuration: 1.5
  trial_count: 31
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.039033381612466
  cueDuration: 0.75
  displayFB: false
  duration: 13.671632670658102
  onset: 348.10550553796446
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.1325992890456373
  stimulusDuration: 1.5
  trial_count: 32
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.052421318568607
  cueDuration: 0.75
  displayFB: false
  duration: 9.498119551881667
  onset: 361.77713820862255
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.94569823331306
  stimulusDuration: 1.5
  trial_count: 33
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.6729909957930706
  cueDuration: 0.75
  displayFB: false
  duration: 7.904484080008679
  onset: 371.2752577605042
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.7314930842156082
  stimulusDuration: 1.5
  trial_count: 34
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.8405951259522038
  cueDuration: 0.75
  displayFB: false
  duration: 9.968102091267493
  onset: 379.17974184051286
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.6275069653152885
  stimulusDuration: 1.5
  trial_count: 35
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.3404189046512327
  cueDuration: 0.75
  displayFB: false
  duration: 8.171255523044653
  onset: 389.14784393178036
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.3308366183934206
  stimulusDuration: 1.5
  trial_count: 36
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.8732706845650935
  cueDuration: 0.75
  displayFB: false
  duration: 7.969550857483659
  onset: 397.319099454825
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.596280172918566
  stimulusDuration: 1.5
  trial_count: 37
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.4049432908010508
  cueDuration: 0.75
  displayFB: false
  duration: 8.382593353520837
  onset: 405.2886503123087
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.4776500627197877
  stimulusDuration: 1.5
  trial_count: 38
  ts: orientation
