- action_keys: [e, b, r, y]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 192
  ori_difficulties:
    ? !!python/tuple [-45, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      +f8QS+0rB0A=
    ? !!python/tuple [45, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      +f8QS+0rB0A=
  quit_key: q
  responseWindow: 1.0
  rp: 0.5
  speed_difficulties:
    ? !!python/tuple [in, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vr+4VssNfj8=
    ? !!python/tuple [out, 0.75]
    : !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Vr+4VssNfj8=
  states:
    0:
      dist_args: {loc: -0.3, scale: 0.37}
      ts: orientation
    1:
      dist_args: {loc: 0.3, scale: 0.37}
      ts: motion
  stim_ids:
  - {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  - {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stim_motions: [in, out]
  stim_oris: [-45, 45]
  subjid: IE
  taskname: cued_dot_task
  trigger_key: '5'
  ts_order: [orientation, motion]
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.060652156333959
  cueDuration: 0.75
  displayFB: false
  duration: 7.216546353411728
  onset: 2
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.6558941970777685
  stimulusDuration: 1.5
  trial_count: 1
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.485115348974859
  cueDuration: 0.75
  displayFB: false
  duration: 8.813006513286453
  onset: 9.216546353411728
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.8278911643115927
  stimulusDuration: 1.5
  trial_count: 2
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.605421245018527
  cueDuration: 0.75
  displayFB: false
  duration: 10.390084461933117
  onset: 18.029552866698182
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 3.2846632169145917
  stimulusDuration: 1.5
  trial_count: 3
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.069057631915114
  cueDuration: 0.75
  displayFB: false
  duration: 7.795122306293099
  onset: 28.4196373286313
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.2260646743779857
  stimulusDuration: 1.5
  trial_count: 4
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.112696041078659
  cueDuration: 0.75
  displayFB: false
  duration: 7.720059925781074
  onset: 36.2147596349244
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.107363884702415
  stimulusDuration: 1.5
  trial_count: 5
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.320706900999046
  cueDuration: 0.75
  displayFB: false
  duration: 11.37532507590084
  onset: 43.93481956070547
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.554618174901794
  stimulusDuration: 1.5
  trial_count: 6
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.2090172177165202
  cueDuration: 0.75
  displayFB: false
  duration: 11.196982636473285
  onset: 55.31014463660631
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 5.487965418756764
  stimulusDuration: 1.5
  trial_count: 7
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.891282341822048
  cueDuration: 0.75
  displayFB: false
  duration: 9.663743312486016
  onset: 66.50712727307959
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 3.272460970663967
  stimulusDuration: 1.5
  trial_count: 8
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.5817817975797368
  cueDuration: 0.75
  displayFB: false
  duration: 10.807129198423205
  onset: 76.17087058556561
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 4.725347400843469
  stimulusDuration: 1.5
  trial_count: 9
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.6506360236100734
  cueDuration: 0.75
  displayFB: false
  duration: 13.150636023610073
  onset: 86.97799978398882
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 6
  stimulusDuration: 1.5
  trial_count: 10
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.8972488995666648
  cueDuration: 0.75
  displayFB: false
  duration: 7.252072941465141
  onset: 100.1286358075989
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.8548240418984757
  stimulusDuration: 1.5
  trial_count: 11
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 5.040269470390476
  cueDuration: 0.75
  displayFB: false
  duration: 11.887969765512814
  onset: 107.38070874906404
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 2.3477002951223382
  stimulusDuration: 1.5
  trial_count: 12
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.007065776982114
  cueDuration: 0.75
  displayFB: false
  duration: 9.040696593251592
  onset: 119.26867851457686
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: 1, speedStrength: 0.75}
  stimResponseInterval: 2.5336308162694774
  stimulusDuration: 1.5
  trial_count: 13
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.348333401315082
  cueDuration: 0.75
  displayFB: false
  duration: 10.311884253191092
  onset: 128.30937510782846
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.463550851876009
  stimulusDuration: 1.5
  trial_count: 14
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.486942118117297
  cueDuration: 0.75
  displayFB: false
  duration: 12.199522725092923
  onset: 138.62125936101955
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.2125806069756249
  stimulusDuration: 1.5
  trial_count: 15
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.544824934259944
  cueDuration: 0.75
  displayFB: false
  duration: 10.380307532804622
  onset: 150.82078208611247
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.3354825985446779
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.559907795606447
  cueDuration: 0.75
  displayFB: false
  duration: 11.747812240843567
  onset: 161.20108961891708
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.68790444523712
  stimulusDuration: 1.5
  trial_count: 17
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.106469000896867
  cueDuration: 0.75
  displayFB: false
  duration: 18.575940534265495
  onset: 172.94890185976064
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 5.969471533368628
  stimulusDuration: 1.5
  trial_count: 18
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.4948320976958964
  cueDuration: 0.75
  displayFB: false
  duration: 8.514213598501428
  onset: 191.52484239402614
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.5193815008055305
  stimulusDuration: 1.5
  trial_count: 19
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.1042179634094835
  cueDuration: 0.75
  displayFB: false
  duration: 8.767151612924176
  onset: 200.03905599252755
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.1629336495146911
  stimulusDuration: 1.5
  trial_count: 20
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.095479522826181
  cueDuration: 0.75
  displayFB: false
  duration: 7.405796027457647
  onset: 208.80620760545173
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.8103165046314666
  stimulusDuration: 1.5
  trial_count: 21
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.5173881980672297
  cueDuration: 0.75
  displayFB: false
  duration: 9.783058236804287
  onset: 216.2120036329094
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.7656700387370585
  stimulusDuration: 1.5
  trial_count: 22
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.855345620068396
  cueDuration: 0.75
  displayFB: false
  duration: 9.297558664004107
  onset: 225.99506186971368
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.9422130439357115
  stimulusDuration: 1.5
  trial_count: 23
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 8.770416360990454
  cueDuration: 0.75
  displayFB: false
  duration: 15.144991340983053
  onset: 235.29262053371778
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: 1, speedStrength: 0.75}
  stimResponseInterval: 1.8745749799925981
  stimulusDuration: 1.5
  trial_count: 24
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.3060561742907193
  cueDuration: 0.75
  displayFB: false
  duration: 6.699569417442275
  onset: 250.43761187470082
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 0.8935132431515551
  stimulusDuration: 1.5
  trial_count: 25
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 3.634742219210642
  cueDuration: 0.75
  displayFB: false
  duration: 10.713449407345978
  onset: 257.1371812921431
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 2.578707188135336
  stimulusDuration: 1.5
  trial_count: 26
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 9.796470280019276
  cueDuration: 0.75
  displayFB: false
  duration: 15.680761107936313
  onset: 267.8506306994891
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.3842908279170363
  stimulusDuration: 1.5
  trial_count: 27
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.861275439706674
  cueDuration: 0.75
  displayFB: false
  duration: 12.376078530365294
  onset: 283.5313918074254
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.0148030906586205
  stimulusDuration: 1.5
  trial_count: 28
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.3558275954272645
  cueDuration: 0.75
  displayFB: false
  duration: 10.546141673285026
  onset: 295.9074703377907
  responseWindow: 1
  stim: {motionDirection: in, oriBase: -45, oriDirection: -1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.6903140778577617
  stimulusDuration: 1.5
  trial_count: 29
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 6.642247595500611
  cueDuration: 0.75
  displayFB: false
  duration: 13.814602391159578
  onset: 306.45361201107573
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 2.6723547956589684
  stimulusDuration: 1.5
  trial_count: 30
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 5.873809791746671
  cueDuration: 0.75
  displayFB: false
  duration: 16.373809791746673
  onset: 320.2682144022353
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 6
  stimulusDuration: 1.5
  trial_count: 31
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.503810836599335
  cueDuration: 0.75
  displayFB: false
  duration: 7.245116392874255
  onset: 336.64202419398197
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.2413055562749202
  stimulusDuration: 1.5
  trial_count: 32
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 5.4721827480646565
  cueDuration: 0.75
  displayFB: false
  duration: 11.5275554920945
  onset: 343.8871405868562
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 1.5553727440298437
  stimulusDuration: 1.5
  trial_count: 33
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.6662012366060965
  cueDuration: 0.75
  displayFB: false
  duration: 7.08155350119221
  onset: 355.4146960789507
  responseWindow: 1
  stim: {motionDirection: in, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.9153522645861135
  stimulusDuration: 1.5
  trial_count: 34
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 10.97427968065159
  cueDuration: 0.75
  displayFB: false
  duration: 17.282381368356106
  onset: 362.49624958014294
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: -1, oriStrength: 0.75,
    speedDirection: -1, speedStrength: 0.75}
  stimResponseInterval: 1.8081016877045175
  stimulusDuration: 1.5
  trial_count: 35
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 4.454961347703589
  cueDuration: 0.75
  displayFB: false
  duration: 10.226546376820462
  onset: 379.778630948499
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: -1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.2715850291168729
  stimulusDuration: 1.5
  trial_count: 36
  ts: orientation
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.9517228072691553
  cueDuration: 0.75
  displayFB: false
  duration: 9.069674753179923
  onset: 390.0051773253195
  responseWindow: 1
  stim: {motionDirection: out, oriBase: -45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 1.6179519459107685
  stimulusDuration: 1.5
  trial_count: 37
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 2.4948352977800763
  cueDuration: 0.75
  displayFB: false
  duration: 11.188247975269574
  onset: 399.0748520784994
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: -1,
    speedStrength: 0.75}
  stimResponseInterval: 4.193412677489499
  stimulusDuration: 1.5
  trial_count: 38
  ts: motion
- CSI: 0.25
  FBDuration: 1
  FBonset: 0
  ITI: 1.0064384355707692
  cueDuration: 0.75
  displayFB: false
  duration: 6.442317659349537
  onset: 410.263100053769
  responseWindow: 1
  stim: {motionDirection: out, oriBase: 45, oriDirection: 1, oriStrength: 0.75, speedDirection: 1,
    speedStrength: 0.75}
  stimResponseInterval: 0.9358792237787683
  stimulusDuration: 1.5
  trial_count: 39
  ts: orientation
