- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 64
  ori_difficulties:
    ? !!python/tuple [-60, medium]
    : 20
    ? !!python/tuple [30, medium]
    : 20
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, medium]
    : 0.06
    ? !!python/tuple [out, medium]
    : 0.06
  stim_ids:
  - &id015 {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id014 {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id013 {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id006 {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id003 {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id002 {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id005 {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id007 {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id004 {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id001 {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id010 {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id016 {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id008 {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id012 {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id011 {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id009 {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE2
  taskname: adaptive_motion
  trigger_key: '5'
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6510141810742178
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id001
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 1
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7260774613790368
  displayFB: true
  onset: 7.651014181074218
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id002
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 2
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.1980466446148288
  displayFB: true
  onset: 13.377091642453255
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id003
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 3
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.1221914851386954
  displayFB: true
  onset: 19.575138287068086
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id004
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 4
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6900417591399687
  displayFB: true
  onset: 25.697329772206782
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id005
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 5
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.156084771820875
  displayFB: true
  onset: 31.38737153134675
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id006
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 6
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.9268118845397494
  displayFB: true
  onset: 37.54345630316763
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id007
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 7
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.0736148421958704
  displayFB: true
  onset: 43.47026818770738
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id008
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 8
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.4897663459242678
  displayFB: true
  onset: 49.543883029903256
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id009
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 9
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6248564592914412
  displayFB: true
  onset: 56.03364937582752
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id006
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 10
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.3822125592757595
  displayFB: true
  onset: 61.658505835118966
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id004
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 11
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.2871621215426514
  displayFB: true
  onset: 68.04071839439473
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id005
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 12
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.281505357421662
  displayFB: true
  onset: 74.32788051593738
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id010
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 13
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.162827599289621
  displayFB: true
  onset: 80.60938587335905
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id001
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 14
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7884134127927659
  displayFB: true
  onset: 86.77221347264867
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id011
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 15
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.8589829974212884
  displayFB: true
  onset: 92.56062688544144
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id007
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 16
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.4189574379199397
  displayFB: true
  onset: 98.41960988286273
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id011
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 17
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.337255996534886
  displayFB: true
  onset: 104.83856732078267
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id012
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 18
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7166413438489203
  displayFB: true
  onset: 111.17582331731757
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id005
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 19
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.2254855667561646
  displayFB: true
  onset: 116.89246466116649
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id002
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 20
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.3733521295107938
  displayFB: true
  onset: 123.11795022792265
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id013
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 21
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6894963156697901
  displayFB: true
  onset: 129.49130235743345
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id014
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 22
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6794025762227293
  displayFB: true
  onset: 135.18079867310325
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id011
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 23
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6153898034469808
  displayFB: true
  onset: 140.860201249326
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id001
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 24
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7523653656160232
  displayFB: true
  onset: 146.47559105277298
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id014
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 25
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.3332033795063127
  displayFB: true
  onset: 152.227956418389
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id012
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 26
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.97151550945411
  displayFB: true
  onset: 158.5611597978953
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id010
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 27
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.214666282049921
  displayFB: true
  onset: 164.53267530734942
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id015
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 28
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.9555381551357387
  displayFB: true
  onset: 170.74734158939935
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id013
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 29
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.5879601882188829
  displayFB: true
  onset: 176.7028797445351
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id007
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 30
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.2331875909564596
  displayFB: true
  onset: 182.29083993275398
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id008
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 31
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.9075821791244293
  displayFB: true
  onset: 188.52402752371043
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id008
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 32
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.9022723494464362
  displayFB: true
  onset: 194.43160970283486
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id013
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 33
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7488795814093419
  displayFB: true
  onset: 200.3338820522813
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id012
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 34
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7984471107242507
  displayFB: true
  onset: 206.08276163369064
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id003
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 35
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.5184288055381394
  displayFB: true
  onset: 211.8812087444149
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id004
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 36
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.1638376921566214
  displayFB: true
  onset: 217.39963754995304
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id010
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 37
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.8672766063978287
  displayFB: true
  onset: 223.56347524210966
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id013
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 38
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.1165256969892177
  displayFB: true
  onset: 229.4307518485075
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id009
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 39
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.8519869828088218
  displayFB: true
  onset: 235.5472775454967
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id016
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 40
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.553062752228698
  displayFB: true
  onset: 241.39926452830554
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id004
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 41
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.2844118074418196
  displayFB: true
  onset: 246.95232728053423
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id006
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 42
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.703471382965594
  displayFB: true
  onset: 253.23673908797605
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id011
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 43
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.046221706009069
  displayFB: true
  onset: 258.9402104709416
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id006
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 44
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6419169509082204
  displayFB: true
  onset: 264.9864321769507
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id010
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 45
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.9695633429972131
  displayFB: true
  onset: 270.62834912785894
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id002
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 46
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6273470580341682
  displayFB: true
  onset: 276.59791247085616
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id003
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 47
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.4038995794441225
  displayFB: true
  onset: 282.2252595288903
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id014
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 48
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7624320930120022
  displayFB: true
  onset: 288.6291591083344
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id009
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 49
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7159772943907735
  displayFB: true
  onset: 294.39159120134644
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id007
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 50
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7044020506449377
  displayFB: true
  onset: 300.1075684957372
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id016
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 51
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.4137752446716754
  displayFB: true
  onset: 305.81197054638216
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id002
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 52
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7684188740324324
  displayFB: true
  onset: 312.22574579105384
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id001
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 53
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.182877068363747
  displayFB: true
  onset: 317.99416466508626
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id003
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 54
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.386157092217686
  displayFB: true
  onset: 324.17704173345
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id005
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 55
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.1521434674071622
  displayFB: true
  onset: 330.56319882566766
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id008
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 56
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.1288335983953326
  displayFB: true
  onset: 336.7153422930748
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id012
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 57
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.0968632488059535
  displayFB: true
  onset: 342.8441758914701
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id014
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 58
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7881579264036263
  displayFB: true
  onset: 348.9410391402761
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id015
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 59
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.0461448999177154
  displayFB: true
  onset: 354.7291970666797
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id015
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 60
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.7662545936841053
  displayFB: true
  onset: 360.7753419665974
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id016
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 61
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.451346786131754
  displayFB: true
  onset: 366.5415965602815
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id015
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 62
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 1.008165737877678
  displayFB: true
  onset: 372.99294334641326
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id016
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 63
  ts: motion
- FBDuration: 1
  FBonset: 0
  ITI: 0.6919293204690894
  displayFB: true
  onset: 379.00110908429093
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id009
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 64
  ts: motion
