- action_keys: [down, up, left, right]
  base_speed: 0.12
  clearAfterResponse: 1
  exp_len: 64
  ori_difficulties:
    ? !!python/tuple [-60, medium]
    : 20
    ? !!python/tuple [30, medium]
    : 20
  quit_key: q
  responseWindow: 1.0
  speed_difficulties:
    ? !!python/tuple [in, medium]
    : 0.06
    ? !!python/tuple [out, medium]
    : 0.06
  stim_ids:
  - &id006 {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id012 {motionDirection: in, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id016 {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id014 {motionDirection: in, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id005 {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id003 {motionDirection: in, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id015 {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id013 {motionDirection: in, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id007 {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id011 {motionDirection: out, oriBase: 30, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id002 {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id008 {motionDirection: out, oriBase: 30, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id004 {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id010 {motionDirection: out, oriBase: -60, oriDirection: -1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  - &id001 {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: -1, speedStrength: medium}
  - &id009 {motionDirection: out, oriBase: -60, oriDirection: 1, oriStrength: medium,
    speedDirection: 1, speedStrength: medium}
  stim_motions: [in, out]
  stim_oris: [-60, 30]
  subjid: IE2
  taskname: adaptive_orientation
  trigger_key: '5'
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4698557381953683
  displayFB: true
  onset: 2
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id001
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 1
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8409652152393262
  displayFB: true
  onset: 8.469855738195369
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id002
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 2
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.2021305084622713
  displayFB: true
  onset: 14.310820953434696
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id003
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 3
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.0221614480923562
  displayFB: true
  onset: 20.512951461896968
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id004
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 4
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.318215081593392
  displayFB: true
  onset: 26.535112909989323
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id005
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 5
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4258057816285588
  displayFB: true
  onset: 32.85332799158272
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id001
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 6
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.3010520754483026
  displayFB: true
  onset: 39.27913377321128
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id006
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 7
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.3170088419362904
  displayFB: true
  onset: 45.58018584865958
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id004
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 8
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4716644690520504
  displayFB: true
  onset: 51.897194690595875
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id007
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 9
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.7956192225487878
  displayFB: true
  onset: 58.368859159647926
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id002
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 10
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.9466241616808738
  displayFB: true
  onset: 64.16447838219672
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id008
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 11
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8560708413308705
  displayFB: true
  onset: 70.11110254387759
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id009
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 12
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.6736386800859621
  displayFB: true
  onset: 75.96717338520847
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id010
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 13
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4871868169153775
  displayFB: true
  onset: 81.64081206529443
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id010
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 14
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.23873717439331
  displayFB: true
  onset: 88.12799888220981
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id004
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 15
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.1808917273601809
  displayFB: true
  onset: 94.36673605660312
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id011
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 16
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.3038156792919542
  displayFB: true
  onset: 100.54762778396329
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id005
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 17
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8659369918073799
  displayFB: true
  onset: 106.85144346325525
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id003
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 18
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8472817832063725
  displayFB: true
  onset: 112.71738045506262
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id004
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 19
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8830316788188075
  displayFB: true
  onset: 118.564662238269
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id012
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 20
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.3543687832794664
  displayFB: true
  onset: 124.4476939170878
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id005
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 21
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.6780483006063122
  displayFB: true
  onset: 130.80206270036726
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id013
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 22
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8227974911960124
  displayFB: true
  onset: 136.48011100097358
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id014
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 23
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4638054734134966
  displayFB: true
  onset: 142.3029084921696
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id011
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 24
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.2950292885922399
  displayFB: true
  onset: 148.76671396558308
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id011
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 25
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.0950622174232445
  displayFB: true
  onset: 155.06174325417533
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id010
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 26
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.0093763227406183
  displayFB: true
  onset: 161.15680547159857
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id007
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 27
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.6781464825026983
  displayFB: true
  onset: 167.1661817943392
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id015
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 28
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.07017426669914
  displayFB: true
  onset: 172.8443282768419
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id015
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 29
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.5742128891822862
  displayFB: true
  onset: 178.91450254354103
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id009
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 30
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4490936411656807
  displayFB: true
  onset: 184.48871543272332
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id008
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 31
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.9184319620521002
  displayFB: true
  onset: 190.937809073889
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id010
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 32
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8653643629682689
  displayFB: true
  onset: 196.8562410359411
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id006
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 33
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.907585057825799
  displayFB: true
  onset: 202.7216053989094
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id012
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 34
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.6355936905634465
  displayFB: true
  onset: 208.6291904567352
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id009
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 35
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.7087657525408322
  displayFB: true
  onset: 214.26478414729863
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id008
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 36
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.80615881321907
  displayFB: true
  onset: 219.97354989983947
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id003
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 37
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.073633319243366
  displayFB: true
  onset: 225.77970871305854
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id013
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 38
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4818091054556024
  displayFB: true
  onset: 231.8533420323019
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id016
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 39
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.0592937574985442
  displayFB: true
  onset: 238.3351511377575
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id013
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 40
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.1807587197236384
  displayFB: true
  onset: 244.39444489525604
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id003
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 41
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.846138015649401
  displayFB: true
  onset: 250.57520361497967
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id002
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 42
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.064306518331287
  displayFB: true
  onset: 256.42134163062906
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id011
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 43
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.7278831895369904
  displayFB: true
  onset: 262.48564814896037
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id014
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 44
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8113784264207987
  displayFB: true
  onset: 268.2135313384974
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id002
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 45
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.2283464692081763
  displayFB: true
  onset: 274.02490976491816
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id007
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 46
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.890346012532699
  displayFB: true
  onset: 280.25325623412635
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id016
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 47
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4007048414927499
  displayFB: true
  onset: 286.14360224665904
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id015
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 48
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4587850450824922
  displayFB: true
  onset: 292.5443070881518
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id016
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 49
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.8414568325510531
  displayFB: true
  onset: 299.0030921332343
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id001
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 50
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.7780114252665131
  displayFB: true
  onset: 304.84454896578535
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id014
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 51
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.336197963997377
  displayFB: true
  onset: 310.6225603910519
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id008
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 52
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.2143891163569496
  displayFB: true
  onset: 316.95875835504927
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id006
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 53
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.698553916898064
  displayFB: true
  onset: 323.1731474714062
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id001
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 54
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.1990779969340386
  displayFB: true
  onset: 328.87170138830425
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id014
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 55
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.854203183314182
  displayFB: true
  onset: 335.07077938523827
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id015
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 56
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.5793372979181118
  displayFB: true
  onset: 340.9249825685524
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id005
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 57
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.4289629508105035
  displayFB: true
  onset: 346.50431986647055
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id016
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 58
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.6041337783479245
  displayFB: true
  onset: 352.93328281728105
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id009
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 59
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.5426404414222648
  displayFB: true
  onset: 358.537416595629
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id013
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 60
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.774547382262748
  displayFB: true
  onset: 364.08005703705123
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id006
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 61
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 1.348924327646157
  displayFB: true
  onset: 369.854604419314
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id012
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 62
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.7536954445164523
  displayFB: true
  onset: 376.20352874696016
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id012
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 63
  ts: orientation
- FBDuration: 1
  FBonset: 0
  ITI: 0.916045117776709
  displayFB: true
  onset: 381.9572241914766
  punishment_amount: 0
  responseWindow: 1.5
  reward_amount: 1
  stim: *id007
  stimResponseInterval: 1
  stimulusDuration: 1.5
  trial_count: 64
  ts: orientation
